version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
  rebase-strategy: disabled
